import os
import re
import yaml
import sys
import traceback
import difflib
import hashlib
import shutil
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import List, Dict, Optional, Tuple, Any
import logging
from jinja2 import Template
from langchain_core.messages import SystemMessage, HumanMessage
from common.utils.util import parse_agent_log, chunk_log_data, load_prompt_config, llm_invoke
from common.llm_dispatch.dispatcher import LLMDispatcherFatalError
from common.utils.prompt_profiles import materialize_prompt_templates
import random
import json
from .node import EvolutionNode, NodeManager
from .codepatcher import CodePatcher
from .refiner_agent import RefinerLLMClient, DaemonThreadPoolExecutor
from .loganalyzer import LogAnalyzer

     
    
class MutatorLLMClient:
    def __init__(self, llm, prompt_cfg_path: str = "cyber_evolver/evolve/prompt.yml", logger=None):
        self.llm = llm
        self.prompt_cfg = load_prompt_config(prompt_cfg_path)
        self.logger = logger or logging.getLogger(self.__class__.__name__)

    def synthesize_plan(self, context: Dict[str, Any], candidate_plans: List[str]) -> str:
        """
        Takes a list of raw evolution plan texts (generated by CodeRefiner)
        and synthesizes them into a single 'Master Plan'.
        """
        if not candidate_plans:
            raise ValueError("Cannot synthesize from empty plan list")

        self.logger.info("⚗️ Mutator: Synthesizing %d plans into a Master Plan...", len(candidate_plans))
         # Format tools for prompt
        tools_str = ""
        for rel_path, content in context.get("tools", {}).items():
            lang = "python" if rel_path.endswith(".py") else "bash" if rel_path.endswith((".sh", ".bash")) else ""
            tools_str += f"## File: {rel_path}\n```{lang}\n{content}\n```\n"

        # Prepare prompts
        system_prompt = self.prompt_cfg.get("system_prompt_mutator")
        user_tmpl_str = self.prompt_cfg.get("user_prompt_mutator")
        
        if not system_prompt or not user_tmpl_str:
            self.logger.error("Missing 'system_prompt_mutator' or 'user_prompt_mutator' in prompt config!")
            raise ValueError("Mutator prompts missing in configuration.")

        # Prepare context for Jinja
        # The prompt expects: {% for i, plan in plans %}
        plans_context = [(i, plan) for i, plan in enumerate(candidate_plans)]

        user_template = Template(user_tmpl_str)
        rendered_prompt = user_template.render(
            agent_implementation=context.get("agent.py", ""),
            prompt_yaml_content=context.get("prompt_templates.yaml", ""),
            tools_context=tools_str,
            plans=plans_context
            )

        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=rendered_prompt)
        ]

        try:
            response = llm_invoke(
                self.llm,
                messages,
                meta={
                    "component": "cyber_evolver.evolve.mutator",
                    "candidate_plan_count": len(candidate_plans),
                },
            )
            content = response.content.strip()
            self.logger.info("✅ Mutation complete. Master Plan length: %d chars", len(content))
            return content
        except Exception as e:
            self.logger.error("Mutator LLM call failed: %s", e, exc_info=True)
            raise


class EvolutionOrchestrator:
    DEFAULT_SEED_INCLUDES = [
        "commands/load_skill.py",
        "skills/skill_template",
    ]

    def __init__(
        self,
        root_dir: str,
        base_seed_path: str,
        llm,
        seed_includes: Optional[List[str]] = None,
        prompt_cfg_path: str = "cyber_evolver/evolve/prompt.yml",
        docker_manager = None,
        logger = None,
        ablation_mode: str = "none",
    ):
        self.root_dir = Path(root_dir)
        self.base_seed_path = Path(base_seed_path)
        combined_seed_includes = list(self.DEFAULT_SEED_INCLUDES) + list(seed_includes or [])
        self.seed_includes = self._normalize_seed_includes(combined_seed_includes)
        self.llm =llm
        self.prompt_cfg_path = prompt_cfg_path
        self.ablation_mode = (ablation_mode or "none").strip().lower()
        self.llm_concurrency = min(32, (os.cpu_count() or 1) * 4)
        self.logger = logger or logging.getLogger(self.__class__.__name__)
        # Sub-modules
        self.node_manager = NodeManager(str(self.root_dir), docker_manager)
        self.log_analyzer = LogAnalyzer(llm, prompt_cfg_path, logger=logger, ablation_mode=self.ablation_mode)
        self.refiner = RefinerLLMClient(llm, prompt_cfg_path, ablation_mode=self.ablation_mode)
        self.mutator = MutatorLLMClient(llm, prompt_cfg_path)
        self.patcher = CodePatcher()

    def _normalize_seed_includes(self, seed_includes: List[str]) -> List[str]:
        normalized: List[str] = []
        seen: set[str] = set()
        for raw_include in seed_includes:
            include_text = str(raw_include or "").strip().replace("\\", "/")
            if not include_text:
                continue
            include_path = Path(include_text)
            if include_path.is_absolute():
                raise ValueError(f"Seed include must be relative to the seed root: {raw_include}")
            normalized_text = include_path.as_posix()
            if normalized_text == "." or normalized_text.startswith("../") or "/../" in normalized_text:
                raise ValueError(f"Seed include must stay inside the seed root: {raw_include}")
            if normalized_text not in seen:
                normalized.append(normalized_text)
                seen.add(normalized_text)
        return normalized

    def _copy_seed_entry(self, source: Path, destination: Path) -> None:
        if source.is_dir():
            shutil.copytree(source, destination)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)

    def _materialize_seed_root(self, destination_dir: Path) -> None:
        seed_root = self.base_seed_path.resolve()
        if not seed_root.exists():
            raise FileNotFoundError(f"Seed root not found: {self.base_seed_path}")

        if destination_dir.exists():
            shutil.rmtree(destination_dir)
        destination_dir.mkdir(parents=True, exist_ok=True)

        for seed_entry in self.base_seed_path.iterdir():
            if seed_entry.name in {"commands", "skills"}:
                continue
            self._copy_seed_entry(seed_entry, destination_dir / seed_entry.name)

        for include_text in self.seed_includes:
            include_rel_path = Path(include_text)
            include_source = (self.base_seed_path / include_rel_path).resolve()
            try:
                include_source.relative_to(seed_root)
            except ValueError as exc:
                raise ValueError(f"Seed include escapes the seed root: {include_text}") from exc

            if not include_source.exists():
                raise ValueError(f"Seed include not found: {include_text}")

            include_parts = include_rel_path.parts
            if not include_parts:
                raise ValueError(f"Seed include is empty: {include_text}")

            top_level = include_parts[0]
            if top_level == "commands":
                if not include_source.is_file():
                    raise ValueError(f"Command include must point to a file: {include_text}")
            elif top_level == "skills":
                if not include_source.is_dir():
                    raise ValueError(f"Skill include must point to a directory: {include_text}")
            else:
                raise ValueError(f"Seed include must be inside commands/ or skills/: {include_text}")

            destination_path = destination_dir / include_rel_path
            if destination_path.exists():
                if destination_path.is_dir():
                    shutil.rmtree(destination_path)
                else:
                    destination_path.unlink()
            self._copy_seed_entry(include_source, destination_path)

    def init_generation_zero(self, chal_data = None) -> List[EvolutionNode]:
        """Initialize G0 root node."""
        self.logger.info("🌱 Initializing Generation 0...")
        existing_node = self.node_manager.get_node("gen0_root")
        if existing_node and existing_node.src_path.exists():
             self._materialize_seed_root(existing_node.src_path)
             materialize_prompt_templates(
                 destination_dir=existing_node.src_path,
                 project_root=Path(__file__).resolve().parents[2],
                 benchmark_family=(chal_data or {}).get("benchmark_family"),
                 prompt_variant=(chal_data or {}).get("default_variant"),
             )
             self.logger.info("🔄 Found existing G0 root node and refreshed prompt overlay: %s", existing_node.node_id)
             return [existing_node]
        # Create new via Manager (automatically registers in tree)
        node = self.node_manager.create_node(gen_id=0, parent_id=None, node_id="gen0_root")
        node.ensure_dirs()
        self._materialize_seed_root(node.src_path)
        materialize_prompt_templates(
            destination_dir=node.src_path,
            project_root=Path(__file__).resolve().parents[2],
            benchmark_family=(chal_data or {}).get("benchmark_family"),
            prompt_variant=(chal_data or {}).get("default_variant"),
        )
        
        self.logger.info("✅ G0 root node created: %s", node.node_id)
        return [node]

    def create_next_generation(self, parents: List[EvolutionNode], children_per_node: int = 2, sample_child: int = 10) -> List[EvolutionNode]:
        """Evolve next generation from parents (parallel over parents)."""
        self.logger.info("🧬 Evolving %d parents → %d children each...", len(parents), children_per_node)
        next_gen = []

        with ThreadPoolExecutor(max_workers=min(len(parents), self.llm_concurrency)) as outer_exec:
            futures = [
                outer_exec.submit(self._evolve_from_parent, parent, children_per_node, sample_child)
                for parent in parents
            ]
            for future in as_completed(futures):
                try:
                    children = future.result()
                    next_gen.extend(children)
                except LLMDispatcherFatalError:
                    raise
                except Exception as e:
                    self.logger.error("Parent evolution failed: %s", e, exc_info=True)

        self.logger.info("✅ Generated %d new children in next generation", len(next_gen))
        return next_gen
    
    
    def _evolve_from_parent(self, parent: EvolutionNode, children_per_node: int = 2, sample_plan_num: int = 10) -> List[EvolutionNode]:
        """ Evolve one parent → sample N plans → Partition into K groups → Synthesize K Master Plans → Create K children."""
        self.logger.info("→ Evolving from parent %s (sample %d plans → select %d)...", 
                        parent.node_id, sample_plan_num, children_per_node)

        # 1. Summarize logs
        p_summaries = parent.get_node_summaries(self.logger)
        self.logger.info("✅ Loaded %d summaries for Parent %s", len(p_summaries), parent.node_id)

        gp_summaries = []
        grandparent = self.node_manager.get_parent(parent)
        if grandparent:
            self.logger.info("🔍 Fetching Grandparent summaries from %s...", grandparent.node_id)
            try:
                gp_summaries = grandparent.get_node_summaries(self.logger)
                self.logger.info("✅ Added %d summaries from Grandparent %s", len(gp_summaries), grandparent.node_id)
            except Exception as e:
                self.logger.exception("⚠️ Failed to load grandparent summaries for %s: %s", grandparent.node_id, e)
        else:
            self.logger.debug("ℹ️ No grandparent found for %s (Likely Gen 0).", parent.node_id)
                
        # 2. Gather context
        context = parent.gather_context()

        # Inject gen0 system_template as an evolution anchor (prevents prompt bloat)
        gen0_st_path = self.base_seed_path / "system_template.txt"
        if gen0_st_path.exists():
            context["gen0_system_template"] = gen0_st_path.read_text(encoding="utf-8")

        # 3. SAMPLING PHASE: generate multiple candidate plans in parallel
        parent.plans_dir.mkdir(parents=True, exist_ok=True)
        raw_plan_texts = []

        # --- Distribute logs to plans ---
        # num_summaries = len(log_summaries)
        # assignments = []

        # if num_summaries > 0:
        #     base_alloc = sample_plan_num // num_summaries
        #     remainder = sample_plan_num % num_summaries
            
        #     for i in range(num_summaries):
        #         alloc = base_alloc + (1 if i < remainder else 0)
        #         summary = log_summaries[i]
        #         for _ in range(alloc):
        #             assignments.append(summary)
        # else:
        #      self.logger.error("❌ No summaries available to generate plans for %s", parent.node_id)
        #      return []
           
        # self.logger.debug("Distribution: Assigning %d summaries to %d plan slots.", len(assignments), sample_plan_num)

        with DaemonThreadPoolExecutor(max_workers=min(sample_plan_num, self.llm_concurrency)) as exec_sample:
            futures = [
                exec_sample.submit(
                    self.refiner.generate_plan,
                    p_summaries,
                    gp_summaries,
                    context,
                    parent.reflection_path / "refiner_failures",
                )
                for i in range(sample_plan_num)
            ]
            # futures = [
            #     exec_sample.submit(self.refiner.generate_plan, [summary], context)
            #     for summary in assignments
            # ]
            for i, future in enumerate(as_completed(futures)):
                try:
                    plan_text = future.result()
                    plan_id = hashlib.sha256(plan_text.strip().encode()).hexdigest()[:8]
                    (parent.plans_dir / f"sample_{i}_{plan_id}.md").write_text(plan_text, encoding="utf-8")
                    raw_plan_texts.append(plan_text)
                    self.logger.debug("Sampled plan %d/%d: %s", i+1, sample_plan_num, plan_id)
                except LLMDispatcherFatalError:
                    raise
                except Exception as e:
                    self.logger.error("Plan sampling failed: %s", e, exc_info=True)

        total_plans = len(raw_plan_texts)
        if total_plans == 0:
            self.logger.error("❌ All %d plan samples failed for %s", sample_plan_num, parent.node_id)
            return []

        # 4. SYNTHESIS / SELECTION PHASE
        master_plans_data = [] # List of (master_id, master_text)

        # --- MODIFICATION START: Skip synthesis if counts match ---
        if total_plans == children_per_node:
            self.logger.info("⚡ Plan count (%d) matches child count. Skipping synthesis; using raw plans directly.", total_plans)
            
            # Directly use raw plans as master plans without LLM synthesis call
            for i, plan_text in enumerate(raw_plan_texts):
                plan_id = hashlib.sha256(plan_text.strip().encode()).hexdigest()[:12]
                
                # Optionally save as a "MASTER" file for consistency (or just rely on previous save)
                # Creating a copy/link as MASTER_direct ensures downstream logic finds it if it looks for "MASTER_"
                master_plan_path = parent.plans_dir / f"MASTER_direct_{i}_{plan_id}.md"
                master_plan_path.write_text(plan_text, encoding="utf-8")
                
                master_plans_data.append((plan_id, plan_text))
        
        else:
            # Original Logic: Group -> Synthesize
            random.shuffle(raw_plan_texts)
            plan_groups = []
            
            if total_plans >= children_per_node:
                # Clean partition
                chunk_size = total_plans // children_per_node
                remainder = total_plans % children_per_node
                start = 0
                for i in range(children_per_node):
                    extra = 1 if i < remainder else 0
                    end = start + chunk_size + extra
                    group = raw_plan_texts[start:end] if raw_plan_texts[start:end] else [raw_plan_texts[0]]
                    plan_groups.append(group)
                    start = end
            else:
                # Reuse/random sample
                self.logger.warning("⚠️ Not enough raw plans (%d) for children (%d). Reusing plans.", total_plans, children_per_node)
                for _ in range(children_per_node):
                    k_sample = max(1, total_plans // 2)
                    plan_groups.append(random.sample(raw_plan_texts, k_sample))

            self.logger.info("⚗️ Synthesizing %d distinct Master Plans from groups...", len(plan_groups))

            # Parallel synthesis
            with DaemonThreadPoolExecutor(max_workers=min(len(plan_groups), self.llm_concurrency)) as exec_synth:
                future_to_idx = {
                    exec_synth.submit(self.mutator.synthesize_plan, context, group): idx 
                    for idx, group in enumerate(plan_groups)
                }
                
                for future in as_completed(future_to_idx):
                    idx = future_to_idx[future]
                    try:
                        master_text = future.result()
                        master_id = hashlib.sha256(master_text.strip().encode()).hexdigest()[:12]
                        
                        master_plan_path = parent.plans_dir / f"MASTER_group{idx}_{master_id}.md"
                        master_plan_path.write_text(master_text, encoding="utf-8")
                        
                        master_plans_data.append((master_id, master_text))
                    except LLMDispatcherFatalError:
                        raise
                    except Exception as e:
                        self.logger.error("Synthesis failed for group %d: %s", idx, e, exc_info=True)
        # --- MODIFICATION END ---

        if not master_plans_data:
            self.logger.error("❌ No master plans available for %s (Synthesis or Direct Selection failed)", parent.node_id)
            return []

        # 5. CHILD CREATION PHASE
        children = []
        available_masters = len(master_plans_data)
        
        with DaemonThreadPoolExecutor(max_workers=min(children_per_node, self.llm_concurrency)) as exec_child:
            futures = []
            for i in range(children_per_node):
                m_id, m_text = master_plans_data[i % available_masters]
                
                futures.append(exec_child.submit(
                    self._create_child_from_plan,
                    parent,
                    i,      # child index
                    m_id,   # plan id
                    m_text  # plan text
                ))

            for future in as_completed(futures):
                try:
                    child = future.result()
                    if child:
                        child.is_mutated = True
                        children.append(child)
                except LLMDispatcherFatalError:
                    raise
                except Exception as e:
                    self.logger.error("Child creation failed: %s", e, exc_info=True)
                    
        return children
    
    def _create_child_from_plan(
        self,
        parent: EvolutionNode,
        idx: int,
        plan_id: str,
        plan_text: str
    ) -> Optional[EvolutionNode]:
        """
        Create ONE child from a pre-selected plan, verify tools, 
        check syntax, and evaluate validity based on tool results and diffs.
        """
        child_id = f"gen{parent.gen_id + 1}_{parent.node_id}_child{idx}"
        self.logger.debug("→ Creating child %s from parent plan %s...", child_id, plan_id)

        try:
            # 1. Setup FS and copy base code from parent
            child = self.node_manager.create_node(
                gen_id=parent.gen_id + 1,
                parent_id=parent.node_id,
                node_id=child_id
            )
            child.ensure_dirs()
            self.node_manager.copy_from_parent(child, str(parent.src_path))

            # 2. Save the mutation plan for traceability
            plan_file_in_child = child.reflection_path / "used_plan.md"
            plan_file_in_child.write_text(plan_text, encoding="utf-8")

            # 3. Apply LLM-generated patches
            patch_log = child.reflection_path / "patch_apply.log"
            summary = self.patcher.apply_patches(child.src_path, plan_text, patch_log)
            self.logger.info("Applied patches for %s: %s", child_id, summary)

            # 4. Verify Syntax and Imports
            # Code must pass basic loading/syntax check first
            syntax_passed, syntax_error = self.node_manager.verify_node_code(child)
            
            # 5. Run Tool Tests in Docker
            # Execute test_*.py scripts to check functional correctness
            failed_tools, tool_msg = self.node_manager.run_tool_tests(child)
            has_tool_failures = len(failed_tools) > 0 if failed_tools else False
            # if tool_msg: 
            #     self.logger.warning("⚠️ test tool msg %s", tool_msg)
            # 6. Compare with Parent to detect changes
            diff_text = self.node_manager.compare_nodes(parent, child)
            is_different_from_parent = diff_text is not None
            if diff_text:
                child.diff_path.write_text(diff_text, encoding="utf-8")
            else:
                child.is_redundant = True

            # 7. Logic-based Validity Assignment:
            # is_code_valid = Code passes verification AND (No tool failures OR Code has changed)
            # This allows code with tool failures to proceed only if it introduced new changes for further evolution.
            if syntax_passed and (not has_tool_failures or is_different_from_parent):
                child.is_code_valid = True
            else:
                child.is_code_valid = False
                
            if not syntax_passed:
                self.logger.warning("⚠️ Child %s failed syntax check: %s", child_id, syntax_error)
                (child.reflection_path / "syntax_error.log").write_text(syntax_error)
            elif has_tool_failures:
                self.logger.warning("⚠️ Child %s has tool failures but is kept due to code changes.", child_id)

            # 8. Enrich child metadata
            child.parent_plan_id = plan_id
            child.plan_id = hashlib.sha256(plan_text.strip().encode()).hexdigest()[:12]
            child.plan_path = str(plan_file_in_child)

            return child

        except Exception as e:
            self.logger.error("❌ Child %s (plan %s) failed during creation: %s", child_id, plan_id, e, exc_info=True)
            error_log = child.reflection_path / "critical_error.log"
            error_log.parent.mkdir(parents=True, exist_ok=True)
            import traceback
            error_log.write_text(traceback.format_exc(), encoding="utf-8")
            return None
