[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tagent"
version = "0.1.0"
description = "A project using OpenAI Agents SDK"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.13.0",
    "openai-agents>=0.0.15",
    "lxml==5.2.1",
    "beautifulsoup4==4.12.3",
    "sqlmap==1.9.5",
]

[project.optional-dependencies]
dev = [
    "black",
    "pytest",
] 