services:
  real-world_cve_vm0:
    build: .
    image: real-world_cve_vm0
    tty: true
    init: true
    networks:
    - net-main_network
    restart: unless-stopped
networks:
  net-main_network: {}
