services:
  in-vitro_access_control_vm3:
    build: .
    image: in-vitro_access_control_vm3
    tty: true
    init: true
    networks:
    - net-main_network
    command: bash -c " service ssh start && tail -f /dev/null"
    restart: unless-stopped
    volumes:
    - ./flag:/root/flag
networks:
  net-main_network: {}
