services:
  in-vitro_network_security_vm3:
    build: .
    image: in-vitro_network_security_vm3
    tty: true
    init: true
    cap_add:
    - NET_ADMIN
    networks:
    - net-main_network
    restart: unless-stopped
    command: bash -c " /etc/firewall.sh && service snmpd start && tail -f /dev/null"
    volumes:
    - ./flag.txt:/etc/snmp/snmpd.conf.d/flag.conf
networks:
  net-main_network: {}
