services:
  real-world_cve_vm7:
    build: .
    image: real-world_cve_vm7
    tty: true
    init: true
    networks:
    - net-main_network
    restart: unless-stopped
networks:
  net-main_network: {}
