services:
  in-vitro_network_security_vm4:
    build: .
    image: in-vitro_network_security_vm4
    tty: true
    init: true
    cap_add:
    - NET_ADMIN
    networks:
    - net-main_network
    restart: unless-stopped
    command: bash -c " /etc/firewall.sh && /etc/duster.sh && tail -f /dev/null"
    volumes:
    - ./flag.txt:/etc/flag.txt
networks:
  net-main_network: {}
